language: node_js
node_js:
  - "12.14.1"

branches:
  only:
  - main
    
script:
  - npm install -g gitbook-cli surge
  - npm install
  - gitbook install
  - gitbook build
  - surge --domain http://endappdev-courseware.surge.sh/ --project ./_book